### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by vinid** [GammaTauAI/leetcode-hard-gym#20]
Hi thanks so much for this!

I am currently experiencing this issue when building the dataset

```
Traceback (most recent call last):
  File "/my/folderopt/leetcode-hard-gym/leetcode_dataset/build.py", line 48, in <module>
    api_instance = get_api_instance()
  File "/my/folderopt/leetcode-hard-gym/leetcode_dataset/lib/utils/utils.py", line 32, in get_api_instance
    csrf_token = leetcode.auth.get_csrf_cookie(leetcode_session)
  File "/my/folder.local/lib/python3.10/site-packages/leetcode/auth.py", line 12, in get_csrf_cookie
    return response.cookies["csrftoken"]
  File "/my/folder.local/lib/python3.10/site-packages/requests/cookies.py", line 334, in __getitem__
    return self._find_no_duplicates(name)
  File "/my/folder.local/lib/python3.10/site-packages/requests/cookies.py", line 413, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='csrftoken', domain=None, path=None"
```

any suggestions on how to fix it?

**Comment by vinid** [comment]
update: this is a problem of the `leetcode-cli` package not of `leetcode-hard-gym`, quick, dirty and bad solution requires to edit "python3.10/site-packages/leetcode/auth.py" to just return your csfr_token
